services:
  # Backend API Service
  - type: web
    name: crm-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: crm-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: crm-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: UPLOAD_PATH
        value: "./uploads"
      - key: ALLOWED_FILE_TYPES
        value: "image/jpeg,image/png,image/gif,application/pdf"

databases:
  # PostgreSQL Database
  - name: crm-postgres
    databaseName: crm_production
    user: crm_user
    plan: starter

  # Redis Cache
  - name: crm-redis
    plan: starter
